import type { Metadata } from "next";
import { ThemeProvider } from "./components/MaterialTailwind";
import { NavbarWithSearch } from "./components/navBar/NavbarWithSearch";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
        <ThemeProvider>
          <body className="bg-surface-900">
            <NavbarWithSearch />
            {children}
          </body>
        </ThemeProvider>
    </html>
  );
}
